name: sap_cco_mobile_agent
description: Inventory management and AI assistant mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  mobile_scanner: ^5.1.1
  http: ^1.2.0
  speech_to_text: ^6.6.0
  camera: ^0.10.5+9
  google_mlkit_image_labeling: ^0.12.0
  
  # State management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  
  # UI enhancements
  flutter_markdown: ^0.7.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Utilities
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/